### ISSUE TITLE
Each of these boxes probably needs a class in common for styling purposes.

### ISSUE THREAD

**Issue by tsdubose** [RUC-web/unit-3-project-Joe-Roman#1]
https://github.com/RUC-web/unit-3-project-Joe-Roman/blob/8596cd61ee26ef261d07bb835f184ab4ca19ed54/index.html#L32

Something like "info-box" or something similar.

**Comment by Joe-Roman** [comment]
Renamed class from "box 1, 2, and 3" to "info-box"
